version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timesheet
    volumes:
      - ./postgres-data:/var/lib/postgresql/datango

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "Teste123"
    ports:
      - "16543:80"
    depends_on:
      - postgres